"""Regenerate authored fixtures with frozen offsets, independent of C structs.

The runtime-v2.save fixture is retained output from revision 04ea5a3, and is
never regenerated by this script.
"""
import hashlib
import json
from pathlib import Path
import struct

ROOT = Path(__file__).parent


def text(payload, offset, value):
    encoded = value.encode("ascii") + b"\0"
    payload[offset:offset + len(encoded)] = encoded


def checksum(payload):
    value = 2166136261
    for byte in payload:
        value = ((value ^ byte) * 16777619) & 0xffffffff
    return value


def operation_fingerprint():
    value = 14695981039346656037
    for byte in b"frozen-study" + struct.pack("<III", 5, 0, 0):
        value = ((value ^ byte) * 1099511628211) & 0xffffffffffffffff
    return value


def authored(version):
    payload = bytearray(5728 if version == 1 else 5760)
    struct.pack_into("<I", payload, 0, version)
    text(payload, 4, "beecho-play-v1-provisional")
    struct.pack_into("<QQ", payload, 48, 1, 1)
    stock = (733, 417, 999) if version == 1 else (700, 400, 900)
    struct.pack_into("<III", payload, 64, *stock)
    struct.pack_into("<II", payload, 108, 10, 1)
    payload[117:121] = bytes([2, 1, 255, 255])
    for index, name in enumerate(("frozen-partial", "frozen-complete")):
        offset = 192 + index * 112
        text(payload, offset, name)
        text(payload, offset + 40, "frozen-expedition")
        struct.pack_into("<I", payload, offset + 104, 1 if index == 0 else 31)
        payload[offset + 109:offset + 112] = bytes([1 if index == 0 else 31, 3, index])
    resident = 1088
    for offset, value in ((0, "frozen-resident"), (40, "frozen-complete"),
                          (80, "parentless-founder"), (104, "design/v1-pip/pip-carried.png"),
                          (144, "pip-playtest-art-v1"), (178, "critter:pip"),
                          (202, "pip-proof-v1"), (226, "pip-rules-v1")):
        text(payload, resident + offset, value)
    payload[resident + 168:resident + 178] = b"CcRrPpMmEe"
    payload[resident + 250:resident + 260] = bytes([1, 1, 0, 1, 1, 1, 3, 1, 0, 1])
    text(payload, 3168, "frozen-study")
    struct.pack_into("<QQ", payload, 3232, 1, operation_fingerprint())
    if version == 2:
        struct.pack_into("<IIIIQ", payload, 5728, 1000, 2000, 3000, 7, 2)
        payload[5752:5755] = bytes([0, 3, 1])
        payload[5755:5760] = b"\xa1\xb2\xc3\xd4\xe5"  # Real V2 checksum includes tail padding.
    header = struct.pack("<8sIII4x", b"BEECHOV1", version, len(payload), checksum(payload))
    return header + payload


for version in (1, 2):
    (ROOT / f"authored-v{version}.save").write_bytes(authored(version))

records = []
for name in ("authored-v1.save", "authored-v2.save", "runtime-v2.save"):
    path = ROOT / name
    if path.exists():
        data = path.read_bytes()
        source = ("native runtime at revision 04ea5a3b41c5b0e988a3c656802b0baa4eec05cb"
                  if name == "runtime-v2.save" else "authored fixed-offset historical ABI")
        records.append({"file": name, "bytes": len(data),
                        "sha256": hashlib.sha256(data).hexdigest(), "source": source})
manifest_path = ROOT / "manifest.json"
if manifest_path.exists():
    regenerated_names = {record["file"] for record in records}
    for record in json.loads(manifest_path.read_text())["fixtures"]:
        if record["file"] not in regenerated_names:
            records.append(record)
manifest_path.write_text(json.dumps({"fixtures": records}, indent=2) + "\n")
