// The V1 roster: 16 species in 16 clans on 16 plans (taxonomy.md §3, the owner's decision of
// 2026-10-07), with each clan's signature. Zacatín, copolí and ocotín carry the open traits and
// fixed values of the authored frames hopper, puffcap and glowtail (species-frames/frames.py);
// the other thirteen are generated by rule from clan, tier and seed (taxonomy.py generate()).
// Names and clans are the cleared ones of taxonomy §5.

const sw = (...ids) => Object.fromEntries(ids.map((id) => [id, "on"]));

export const CLANS = {
  trebola: { number: 1, plan: "one|serial|bilateral|contact|zero|one|two|off|skin", extras: { join: "broad" }, anchor: "charcoal", second: "cream", feature: "leaf crest and snout", features: sw("anatomy.muzzle-presence", "anatomy.crown-presence", "appearance.belly-field"), finish: { "anatomy.crown-form": "pointed", "growth.crest-leaf-count": "three" }, glyphTop: ["#.#.#", ".###."] },
  algodina: { number: 2, plan: "one|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "broad" }, anchor: "periwinkle", second: "cream", feature: "long round ears", features: sw("anatomy.muzzle-presence", "anatomy.auricular-presence"), finish: { "anatomy.auricular-form": "rounded", "growth.auricular-length-ratio": "long", "appearance.fur-flow": "axial" }, glyphTop: ["#...#", "##.##"] },
  bonetia: { number: 3, plan: "one|serial|radial|none|zero|one|two|on|fur", extras: { join: "broad", wave: true }, anchor: "coral", second: null, feature: "a cap on top", features: sw("anatomy.top-cap-sheet"), finish: {}, glyphTop: [".###.", "#####"] },
  felpina: { number: 4, plan: "two|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "narrow", wave: true }, anchor: "russet", second: "peach", feature: "pointed ears and a plush tail", features: sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence"), finish: { "anatomy.auricular-form": "pointed", "growth.auricular-length-ratio": "long", "appearance.fur-length": "long" }, glyphTop: ["#...#", ".#.#."] },
  zancola: { number: 5, plan: "two|serial|bilateral|free|three|two|two|off|skin", extras: { join: "narrow" }, anchor: "jade", second: "ice", feature: "six stilt feelers and thread antennae", features: sw("anatomy.antenna-presence"), finish: { "anatomy.antenna-form": "thread", "growth.free-proximal-ratio": "long" }, glyphTop: [".#.#.", "#.#.#"] },
  limacela: { number: 6, plan: "three|serial|bilateral|none|zero|one|two|off|skin", extras: { join: "broad", wave: true }, anchor: "plum", second: "butter", feature: "eye stalks and a foot skirt", features: sw("anatomy.antenna-presence", "anatomy.foot-skirt-presence"), finish: { "anatomy.antenna-form": "club", "appearance.sheen": "glossy", "development.regional-growth": "anterior" }, glyphTop: [".###.", "#...#"] },
  fanalia: { number: 7, plan: "two|serial|bilateral|contact|zero|one|two|off|scales", extras: { join: "narrow", wave: true }, anchor: "lagoon", second: "milk-mint", feature: "a long tail that glows", features: sw("anatomy.muzzle-presence", "anatomy.crown-presence", "anatomy.axial-tail-presence", "anatomy.tail-tip-bulb"), finish: { "anatomy.crown-form": "pointed" }, glyphTop: ["..#..", ".###."] },
  erizola: { number: 8, plan: "one|serial|radial|contact|zero|one|two|off|fur", extras: { join: "broad" }, anchor: "raspberry", second: null, feature: "a furred dome on six short rays", features: {}, finish: { "appearance.fur-length": "long" }, glyphTop: ["#.#.#", ".###."] },
  flotela: { number: 9, plan: "one|serial|radial|free|three|two|two|off|skin", extras: { join: "broad", wave: true, float: true }, anchor: "periwinkle", second: null, feature: "nine trailing feelers", features: {}, finish: { "appearance.sheen": "glossy", "growth.free-distal-ratio": "long" }, glyphTop: [".###.", "#.#.#"] },
  volanta: { number: 10, plan: "three|serial|bilateral|contact|zero|one|three|on|skin", extras: { join: "narrow" }, anchor: "marigold", second: "butter", feature: "club antennae and wide flaps", features: sw("anatomy.antenna-presence"), finish: { "anatomy.antenna-form": "club", "growth.wing-span-ratio": "long" }, glyphTop: ["#...#", ".#.#."] },
  caparela: { number: 11, plan: "three|serial|bilateral|contact|zero|one|three|off|scales", extras: { join: "narrow" }, anchor: "charcoal", second: "slate", feature: "wing cases and digging wedges", features: sw("anatomy.antenna-presence", "anatomy.wing-case-presence"), finish: { "anatomy.antenna-form": "thread", "anatomy.contact-terminal-form": "wedge" }, glyphTop: [".###.", "##.##"] },
  aletia: { number: 12, plan: "three|serial|bilateral|none|zero|one|two|on|scales", extras: { join: "narrow", wave: true, fins: true }, anchor: "cobalt", second: "ice", feature: "a back fin and a tail", features: sw("anatomy.muzzle-presence", "anatomy.crown-presence", "anatomy.axial-tail-presence"), finish: { "anatomy.crown-form": "pointed", "appearance.anatomical-scale-size": "fine" }, glyphTop: ["..#..", ".###."] },
  penacha: { number: 13, plan: "one|serial|bilateral|contact|zero|one|two|on|fur", extras: { join: "broad" }, anchor: "plum", second: "peach", feature: "a plumed crest and furred flaps", features: sw("anatomy.muzzle-presence", "anatomy.crown-presence", "anatomy.auricular-presence"), finish: { "anatomy.crown-form": "pointed", "growth.crown-height-ratio": "high", "anatomy.auricular-form": "pointed" }, glyphTop: [".#.#.", "#####"] },
  ondela: { number: 14, plan: "two|fan|bilateral|none|zero|one|two|on|skin", extras: { join: "narrow", wave: true, fins: true }, anchor: "lagoon", second: "ice", feature: "two swept lobes and a tail", features: sw("anatomy.axial-tail-presence"), finish: { "growth.branch-angle": "wide" }, glyphTop: ["#.#.#", "#####"] },
  brotela: { number: 15, plan: "two|fan|radial|contact|zero|one|two|off|skin", extras: { join: "broad" }, anchor: "jade", second: null, feature: "leaves on three lobes, walking on root feet", features: sw("anatomy.leaf-presence", "anatomy.root-foot-presence"), finish: { "appearance.leaf-covering": "leafy" }, glyphTop: [".#.#.", "##.##"] },
  lirela: { number: 16, plan: "three|fan|radial|none|zero|one|two|on|skin", extras: { join: "broad", float: true }, anchor: "raspberry", second: null, feature: "petals round a floating hub", features: sw("anatomy.leaf-presence", "anatomy.petal-presence"), finish: { "appearance.leaf-covering": "leafy" }, glyphTop: [".###.", "#.#.#"] },
};

const tax = (name, root, moves, habitat, tier, gate = null, diet = null, ability = null) => ({ name, root, moves, habitat, tier, gate, diet, ability });

// The three authored frames, as frames.py defines them (open traits, pools, fixed values).
const ZACATIN_FIXED = {
  "growth.core-half-length": "medium", "growth.core-width-ratio": "high", "growth.core-depth-ratio": "high",
  "growth.head-length-ratio": "large", "growth.head-width-ratio": "high", "growth.head-depth-ratio": "high",
  "growth.head-lift-ratio": "low", "growth.muzzle-projection-ratio": "short", "growth.muzzle-width-ratio": "high",
  "growth.exterior-eye-spacing-ratio": "wide", "growth.crown-height-ratio": "high",
  "growth.support-drop-ratio": "short", "growth.support-radius-ratio": "stout", "growth.support-splay-ratio": "low",
  "growth.terminal-length-ratio": "broad", "growth.terminal-depth-ratio": "high",
  "anatomy.contact-terminal-form": "pad", "anatomy.region-longitudinal-form": "barrel",
  "appearance.marking-layout": "patches", "appearance.marking-extent": "high", "appearance.marking-scale": "high",
  "appearance.marking-contrast": "high", "cognition.exploration-tendency": "seeking", "cognition.arousal-threshold": "low",
};
const COPOLI_FIXED = {
  "growth.core-half-length": "large", "growth.head-length-ratio": "small", "growth.head-width-ratio": "low",
  "growth.head-depth-ratio": "low", "growth.head-lift-ratio": "low", "growth.exterior-eye-size-ratio": "large",
  "growth.exterior-eye-spacing-ratio": "wide", "movement.membrane-stroke": "low", "movement.membrane-coordination": "high",
  "energy.actuator-capacity": "low", "energy.reserve-capacity": "high", "energy.action-efficiency": "low",
};
const OCOTIN_FIXED = {
  "growth.core-half-length": "small", "growth.head-length-ratio": "medium", "growth.head-width-ratio": "high",
  "growth.head-depth-ratio": "high", "growth.head-lift-ratio": "low", "growth.join-throat-ratio": "broad",
  "growth.support-splay-ratio": "high", "anatomy.region-cross-exponent": "round", "anatomy.region-longitudinal-form": "tapered",
};

export const SPECIES = [
  { id: "zacatin", name: "Zacatín", plural: "zacatines", order: 1, clan: "trebola", tier: "starter", seed: 1,
    summary: "The starter: Pip as in the approved art. Exactly the five open traits of the Pip proof.",
    taxonomy: tax("Zacatín", "zacate, the meadow grass it hops through", "hops", "meadow, pond edge", "starter", null, "fruit", null),
    fixed: ZACATIN_FIXED, openSwitches: ["appearance.marking-switch", "anatomy.crown-presence"],
    open: [
      { chapter: "coat", id: "markings", name: "Markings", loci: ["appearance.marking-switch"], looks: ["plain", "pale patches"] },
      { chapter: "face", id: "crown", name: "Crown", loci: ["anatomy.crown-presence"], looks: ["bare head", "leaf crest"] },
      { chapter: "face", id: "eye-rings", name: "Eye rings", loci: ["growth.exterior-eye-size-ratio"], looks: ["thin rings", "between", "wide pale rings"] },
      { chapter: "movement", id: "drive", name: "Drive", loci: ["movement.cycle-rate"], looks: ["steady", "between", "bursts"] },
      { chapter: "stamina", id: "efficiency", name: "Efficiency", loci: ["energy.action-efficiency"], looks: ["thrifty", "between", "ordinary"] },
    ],
    sealed: {}, glyph: ["#.#.#", ".###.", "#####", "#####", "#.#.#"],
    pending: [{ trait: "orange eyes", why: "eye rim and pupil are fixed inks" }] },
  { id: "lanoli", name: "Lanolí", plural: "lanolíes", order: 2, clan: "algodina", tier: "starter", seed: 1,
    taxonomy: tax("Lanolí", "lana, wool", "grazes, trots", "meadow", "starter"), sealed: {} },
  { id: "copoli", name: "Copolí", plural: "copolíes", order: 3, clan: "bonetia", tier: "early", seed: 1,
    summary: "A radial, capped plan: a round furred body, a face, a cap on top, no legs. It waddles.",
    taxonomy: tax("Copolí", "copo, a tuft under its cap", "waddles", "wood, meadow, pond", "early", "Ways sealed (crystal)", "fruit", "sniffs out buried pods"),
    fixed: COPOLI_FIXED, openSwitches: ["appearance.marking-switch"],
    open: [
      { trait: "colour", pool: { "appearance.body-palette": ["coral", "raspberry", "marigold", "plum"] }, looks: ["coral", "raspberry", "marigold", "plum", "two side by side"] },
      { trait: "markings", name: "Spots", looks: ["bare", "bands", "spots", "bands and spots"] },
      { trait: "fluff" }, { trait: "roundness" }, { trait: "body" },
      { chapter: "shape", id: "cap-size", name: "Cap size", loci: ["growth.wing-span-ratio", "growth.wing-chord-ratio"], looks: ["small cap", "between", "wide cap"] },
      { trait: "cap-colour" }, { trait: "cap-spots" },
      { trait: "pace" }, { trait: "turning" },
      { chapter: "movement", id: "waddle", name: "Waddle", loci: ["movement.axial-amplitude", "movement.axial-phase"], looks: ["slight sway", "between", "big waddle"] },
      { trait: "curiosity" }, { trait: "nerve" },
    ],
    sealed: { ways: "a vybronic crystal, dug up where a copolí partner sniffs out a buried pod" }, glyph: [".###.", "#####", "#####", ".#.#.", ".###."], pod: { second: "marigold" } },
  { id: "orejolo", name: "Orejolo", plural: "orejolos", order: 4, clan: "felpina", tier: "early", seed: 1,
    taxonomy: tax("Orejolo", "oreja, its pointed ears", "prowls", "wood, meadow", "early"), sealed: {} },
  { id: "puntilu", name: "Puntilú", plural: "puntilúes", order: 5, clan: "zancola", tier: "early", seed: 1,
    taxonomy: tax("Puntilú", "de puntillas, on tiptoe", "tiptoes on many feelers", "wood", "early"), sealed: {} },
  { id: "musguin", name: "Musguín", plural: "musguines", order: 6, clan: "limacela", tier: "early", seed: 1,
    taxonomy: tax("Musguín", "musgo, the moss it eats", "slides (a slug)", "pond edge, wood; out in fog banks", "early", null, "moss"), sealed: {} },
  { id: "ocotin", name: "Ocotín", plural: "ocotines", order: 7, clan: "fanalia", tier: "mid", seed: 1,
    summary: "A tailed, scaled burrower: a low two-part body, four short legs, a crest, a long tail that carries the glow.",
    taxonomy: tax("Ocotín", "ocote, the pine lit as a torch: its glow", "scurries, digs, glows", "wood, rock field", "mid", "opens narrow holes, Night", "fruit", "digs"),
    fixed: OCOTIN_FIXED, openSwitches: ["appearance.marking-switch"],
    open: [
      { trait: "colour", pool: { "appearance.body-palette": ["lagoon", "jade", "marigold", "periwinkle"] }, looks: ["lagoon", "jade", "marigold", "periwinkle", "two side by side"] },
      { trait: "second-colour", name: "Leg colour", pool: { "appearance.underside-palette": ["milk-mint", "cream", "ice", "slate"] }, looks: ["milk-mint", "cream", "ice", "slate", "two side by side"] },
      { trait: "markings", looks: ["plain", "stripes", "spots", "stripes and spots"] }, { trait: "scales" },
      { chapter: "face", id: "crest", name: "Crest", loci: ["growth.crown-height-ratio"], looks: ["low crest", "between", "tall crest"] },
      { trait: "eyes" }, { trait: "snout" }, { trait: "build" }, { trait: "hind-body" }, { trait: "back-line" },
      { chapter: "legs-tail", id: "legs", name: "Legs", loci: ["growth.support-drop-ratio", "growth.support-radius-ratio"], looks: ["short, fine", "between", "long, stout"] },
      { trait: "feet", name: "Claws", shapeable: false, override: "breeding only: the claws are how an ocotín digs, a field ability, so they change like a doing" },
      { trait: "tail" }, { trait: "tail-curl" }, { trait: "pace" }, { trait: "stride" },
      { chapter: "movement", id: "weave", name: "Weave", loci: ["movement.axial-amplitude", "movement.axial-phase"], looks: ["straight scurry", "between", "weaving glide"] },
      { trait: "turning" }, { trait: "strength" }, { trait: "reserve" }, { trait: "thrift" }, { trait: "curiosity" }, { trait: "nerve" },
      { trait: "glow", shapeable: false }, { trait: "glow-length", shapeable: false },
    ],
    sealed: {}, glyph: ["..#..", ".###.", "..#..", "..#..", "#####"], pod: { second: "marigold" } },
  { id: "tambolo", name: "Tambolo", plural: "tambolos", order: 8, clan: "erizola", tier: "mid", seed: 1,
    taxonomy: tax("Tambolo", "tambalear, to wobble", "wobbles on many short legs", "rock field", "mid"), sealed: {} },
  { id: "charquin", name: "Charquín", plural: "charquines", order: 9, clan: "flotela", tier: "mid", seed: 1,
    taxonomy: tax("Charquín", "charco, the pond it drifts in", "drifts, trailing feelers", "pond", "mid"), sealed: {} },
  { id: "petalu", name: "Petalú", plural: "petalúes", order: 10, clan: "volanta", tier: "mid", seed: 1,
    taxonomy: tax("Petalú", "pétalo, petal-shaped flaps", "flutters (insect-like)", "meadow", "mid"), sealed: { stamina: "a storm-glass shard" }, alwaysOpen: ["flap-markings", "translucency"] },
  { id: "cavito", name: "Cavito", plural: "cavitos", order: 11, clan: "caparela", tier: "mid", seed: 1,
    taxonomy: tax("Cavito", "cavar, to dig", "crawls, digs (beetle-like)", "rock field, cave", "mid", "Deep ground", null, "digs"), sealed: {}, alwaysOpen: ["wing-cases"] },
  { id: "remoli", name: "Remolí", plural: "remolíes", order: 12, clan: "aletia", tier: "mid", seed: 1,
    taxonomy: tax("Remolí", "remolino, whirl in fast water", "swims", "pond, fast water", "mid", "opens fast water", null, "swims"), sealed: { ways: "a tide pearl" } },
  { id: "brisu", name: "Brisú", plural: "brisúes", order: 13, clan: "penacha", tier: "late", seed: 1,
    taxonomy: tax("Brisú", "brisa, the breeze it glides on", "glides (bat-like)", "wood, rock field", "late", "Night"), sealed: {}, alwaysOpen: ["flaps", "flap-markings"] },
  { id: "arroyin", name: "Arroyín", plural: "arroyines", order: 14, clan: "ondela", tier: "late", seed: 1,
    taxonomy: tax("Arroyín", "arroyo, brook", "glides underwater", "beyond fast water", "late", "needs a swimmer"), sealed: { movement: "a tide pearl" }, alwaysOpen: ["translucency"] },
  { id: "hojarin", name: "Hojarín", plural: "hojarines", order: 15, clan: "brotela", tier: "late", seed: 1,
    taxonomy: tax("Hojarín", "hoja, leaf", "walks on its roots (a plant)", "wood", "late", "sealed chapter", "light"), sealed: { stamina: "a storm-glass shard" }, alwaysOpen: ["leaves", "roots", "light-feeding"] },
  { id: "nenufi", name: "Nenufí", plural: "nenufíes", order: 16, clan: "lirela", tier: "late", seed: 1,
    taxonomy: tax("Nenufí", "nenúfar, water lily", "floats, opens its petals (a plant)", "pond", "late", "the deep ? (tier 2)", "light"), sealed: {}, alwaysOpen: ["petals", "leaves", "light-feeding"] },
];

export function specOf(species) {
  const clan = CLANS[species.clan];
  const member = SPECIES.filter((s) => s.clan === species.clan).indexOf(species) + 1;
  return {
    ...species,
    plan: { key: clan.plan, extras: clan.extras }, anchor: clan.anchor, second: clan.second, feature: clan.feature,
    features: { "anatomy.exterior-eye-presence": "on", ...clan.features }, // always a face: a pet has eyes (taxonomy §3)
    fixed: { ...clan.finish, ...(species.fixed ?? {}) }, finish: clan.finish,
    taxonomy: { ...species.taxonomy, clanNumber: clan.number, member, speciesNumber: clan.number * 32 + member, binomial: `${species.clan[0].toUpperCase()}${species.clan.slice(1)} ${species.id}` },
    glyph: species.glyph ?? [...clan.glyphTop, ...glyphRows(`${species.clan}:${species.id}`)],
  };
}
function glyphRows(seed) {
  let a = 0;
  for (const ch of seed) a = (Math.imul(a ^ ch.charCodeAt(0), 0x01000193) + 7) >>> 0;
  const rows = [];
  for (let i = 0; i < 3; i++) {
    const half = [0, 1, 2].map(() => { a = (Math.imul(a, 1664525) + 1013904223) >>> 0; return a >>> 31 ? "#" : "."; });
    if (half.join("") === "...") half[2] = "#";
    rows.push([...half, half[1], half[0]].join(""));
  }
  return rows;
}
