// The V1 roster: 16 species in 16 clans (taxonomy.md §3, the owner's decisions of 2026-10-07: a
// roster with cat-, fox- and raccoon-like mammals, at most two insect-like kinds, more big animals
// across size classes; the slug, the plant and the lightning kind stay as the strange ones). The
// codes S01–S16 and C01–C16 are the ids; the names are the approved ones of species-names.md
// (the copywriter's, §5) and ride beside the codes. S01, S02 and S03 carry the open traits and
// fixed values of the authored frames hopper, puffcap and glowtail (species-frames/frames.py); the
// other thirteen are generated by rule from clan, tier and seed (taxonomy.py generate()).
// Each clan's signature is the "signature look" and "clan" columns of §3's copywriter table;
// `parts` are the clan's defining parts, the ones the kind check's parts score measures (targets.mjs).

// The approved names (design/proposals/species-names.md): one per species, one per clan. The clan
// name doubles as the genus on the tome's clan plate, so S01 is Lophessa loika.
export const SPECIES_NAMES = { S01: "Loika", S02: "Untuva", S03: "Tuikis", S04: "Hiljan", S05: "Tepor", S06: "Pesko", S07: "Azkon", S08: "Rupar", S09: "Belatz", S10: "Igara", S11: "Kilpo", S12: "Peplos", S13: "Oskol", S14: "Usvel", S15: "Lehten", S16: "Blikur" };
export const CLAN_NAMES = { C01: "Lophessa", C02: "Kausida", C03: "Stilbera", C04: "Lathreta", C05: "Dasyla", C06: "Prosopa", C07: "Skapana", C08: "Kremnion", C09: "Aithria", C10: "Kolymba", C11: "Thyreka", C12: "Graptoma", C13: "Lepidos", C14: "Kapnis", C15: "Phyllaxa", C16: "Brontelas" };

import { proportionPairs } from "./proportions.mjs";

const sw = (...ids) => Object.fromEntries(ids.map((id) => [id, "on"]));
const EYES = sw("anatomy.exterior-eye-presence"); // always a face: a pet has eyes (taxonomy §3)

export const CLANS = {
  C01: { number: 1, resembles: "a round frog-hare, Pip", parts: ["crest","leg","head","body"], plan: "one|serial|bilateral|contact|zero|one|two|off|skin", extras: { join: "broad" }, anchor: "charcoal", second: "cream", feature: "a leaf crest and a snout; charcoal", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.crown-presence", "appearance.belly-field") }, finish: { "anatomy.crown-form": "leaf", "growth.crest-leaf-count": "three" }, glyphTop: ["#.#.#", ".###."] },
  C02: { number: 2, resembles: "a puffball under a cap", parts: ["flap","head"], plan: "one|serial|radial|none|zero|one|two|on|fur", extras: { join: "broad", wave: true }, anchor: "coral", second: null, feature: "a cap of flaps, coral, radial bodies; soft, round, sleepy", features: { ...EYES, ...sw("anatomy.top-cap-sheet") }, finish: { "appearance.flap-translucency": "opaque" }, glyphTop: [".###.", "#####"] },
  C03: { number: 3, resembles: "a lizard with a lantern tail", parts: ["tail","crest","leg"], plan: "two|serial|bilateral|contact|zero|one|two|off|scales", extras: { join: "narrow", wave: true }, anchor: "lagoon", second: "milk-mint", feature: "a glowing tail and a crest, lagoon; small lights of wood and rock", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.crown-presence", "anatomy.axial-tail-presence", "anatomy.tail-tip-bulb") }, finish: { "anatomy.crown-form": "pointed" }, glyphTop: ["..#..", ".###."] },
  C04: { number: 4, resembles: "a cat", parts: ["ear","muzzle","tail","head"], plan: "two|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "narrow", wave: true }, anchor: "russet", second: "cream", feature: "upright pointed ears, striped fur; quiet hunters of the grass", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence", "appearance.marking-switch") }, finish: { "anatomy.auricular-form": "pointed", "anatomy.ear-tilt": "upright", "growth.muzzle-projection-ratio": "short", "growth.axial-tail-length-ratio": "long", "appearance.marking-layout": "bands", "appearance.fur-reach": "body", "anatomy.contact-terminal-form": "pad" }, glyphTop: ["#...#", ".#.#."] },
  C05: { number: 5, resembles: "a fox", parts: ["muzzle","ear","tail"], plan: "two|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "narrow" }, anchor: "marigold", second: "cream", feature: "tall ears, a long muzzle, a bushy tail; clever wanderers", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence", "appearance.tail-rings") }, finish: { "anatomy.auricular-form": "pointed", "growth.auricular-length-ratio": "long", "anatomy.ear-tilt": "upright", "growth.muzzle-projection-ratio": "long", "appearance.fur-reach": "tail", "growth.axial-tail-width-ratio": "broad", "growth.tail-ring-count": "one", "anatomy.contact-terminal-form": "pad" }, glyphTop: ["#...#", "##.##"] },
  C06: { number: 6, resembles: "a raccoon", parts: ["muzzle","ear","tail"], plan: "two|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "narrow" }, anchor: "charcoal", second: "slate", feature: "a face mask and a ringed tail; masked tinkerers", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence", "appearance.face-mask", "appearance.tail-rings") }, finish: { "anatomy.auricular-form": "rounded", "appearance.face-mask-shape": "band", "growth.tail-ring-count": "four", "appearance.fur-reach": "tail", "anatomy.contact-terminal-form": "pad" }, glyphTop: ["#####", ".#.#."] },
  C07: { number: 7, resembles: "a badger or small bear", parts: ["muzzle","ear","leg","tail"], plan: "one|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "broad" }, anchor: "russet", second: "cream", feature: "broad claws, a striped face, stout bodies; the diggers", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "appearance.face-mask") }, finish: { "anatomy.auricular-form": "rounded", "growth.auricular-length-ratio": "short", "appearance.face-mask-shape": "stripes", "anatomy.contact-terminal-form": "wedge", "growth.terminal-length-ratio": "broad", "growth.core-width-ratio": "high", "growth.core-depth-ratio": "high" }, glyphTop: [".###.", "#.#.#"] },
  C08: { number: 8, resembles: "a goat or deer", parts: ["crest","leg","muzzle"], plan: "two|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "narrow" }, anchor: "russet", second: "butter", feature: "horns and hooves; climbers of the high rocks", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence", "anatomy.horn-presence") }, finish: { "anatomy.contact-terminal-form": "hoof", "growth.support-drop-ratio": "long", "growth.support-radius-ratio": "slender", "growth.axial-tail-length-ratio": "short", "growth.muzzle-projection-ratio": "long" }, glyphTop: ["#...#", ".#.#."] },
  C09: { number: 9, resembles: "a big bird", parts: ["muzzle","leg","crest","tail"], plan: "two|serial|bilateral|contact|zero|one|one|on|fur", extras: { join: "narrow", flapRest: "flat" }, anchor: "cobalt", second: "butter", feature: "wings and a beak; big birds of open sky", features: { ...EYES, ...sw("anatomy.beak-presence", "anatomy.crown-presence", "appearance.feather-presence", "anatomy.axial-tail-presence") }, finish: { "anatomy.crown-form": "pointed", "growth.wing-span-ratio": "long", "growth.wing-chord-ratio": "wide", "appearance.flap-translucency": "opaque", "growth.support-drop-ratio": "long", "growth.support-radius-ratio": "slender", "anatomy.contact-terminal-form": "rounded" }, glyphTop: [".#.#.", "#####"] }, // bird feet rounded, not wedges; slender legs (the envelope's leg floor made fine ones stout anyway)
  C10: { number: 10, resembles: "an otter", parts: ["tail","leg","muzzle"], plan: "three|serial|bilateral|contact|zero|one|two|off|fur", extras: { join: "broad", wave: true }, anchor: "russet", second: "peach", feature: "long sleek bodies and webbed paws; the water players", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.auricular-presence", "anatomy.axial-tail-presence") }, finish: { "anatomy.contact-terminal-form": "webbed", "anatomy.auricular-form": "rounded", "growth.auricular-length-ratio": "short", "growth.axial-tail-width-ratio": "broad", "growth.support-drop-ratio": "short", "appearance.fur-length": "short" }, glyphTop: ["##.##", "#####"] },
  C11: { number: 11, resembles: "a turtle", parts: ["shell","leg","head"], plan: "one|serial|bilateral|contact|zero|one|two|off|scales", extras: { join: "narrow" }, anchor: "jade", second: "butter", feature: "a shell; slow keepers of the pond", features: { ...EYES, ...sw("anatomy.muzzle-presence", "anatomy.shell-presence") }, finish: { "growth.support-drop-ratio": "short", "growth.support-splay-ratio": "high", "anatomy.contact-terminal-form": "rounded", "appearance.anatomical-scale-size": "coarse" }, glyphTop: [".###.", "#####"] },
  C12: { number: 12, resembles: "a moth or butterfly", parts: ["flap","antenna","leg"], plan: "three|serial|bilateral|contact|zero|one|three|on|skin", extras: { join: "narrow", flapPairs: 2, flapRest: "flat" }, anchor: "marigold", second: "butter", feature: "patterned flaps; fliers of the flowers", features: { ...EYES, ...sw("anatomy.antenna-presence") }, finish: { "anatomy.antenna-form": "feather", "growth.wing-span-ratio": "long", "growth.wing-chord-ratio": "wide", "growth.support-radius-ratio": "fine" }, glyphTop: ["#...#", ".#.#."] },
  C13: { number: 13, resembles: "a beetle", parts: ["antenna","leg","shell"], plan: "three|serial|bilateral|contact|zero|one|three|off|scales", extras: { join: "narrow" }, anchor: "charcoal", second: "slate", feature: "plates and wing cases; armoured crawlers", features: { ...EYES, ...sw("anatomy.antenna-presence", "anatomy.wing-case-presence") }, finish: { "anatomy.antenna-form": "thread", "anatomy.contact-terminal-form": "wedge", "appearance.anatomical-scale-size": "coarse" }, glyphTop: [".###.", "##.##"] },
  C14: { number: 14, resembles: "a slug", parts: ["antenna","skirt","body"], plan: "three|serial|bilateral|none|zero|one|two|off|skin", extras: { join: "broad", wave: true }, anchor: "plum", second: "butter", feature: "eye stalks and a sheen; the fog-lovers", features: { ...EYES, ...sw("anatomy.antenna-presence", "anatomy.foot-skirt-presence") }, finish: { "anatomy.antenna-form": "club", "appearance.sheen": "glossy", "development.regional-growth": "anterior" }, glyphTop: [".###.", "#...#"] },
  C15: { number: 15, resembles: "a walking plant", parts: ["leaf","leg","body"], plan: "two|fan|radial|contact|zero|one|one|off|skin", extras: { join: "broad", stand: true }, anchor: "jade", second: null, feature: "leaves and roots; the walking green", features: { ...EYES, ...sw("anatomy.leaf-presence") }, finish: { "appearance.leaf-covering": "leafy", "anatomy.contact-terminal-form": "root" }, glyphTop: [".#.#.", "##.##"] },
  C16: { number: 16, resembles: "a wisp of lightning", parts: ["body","head"], plan: "three|fan|bilateral|none|zero|one|two|off|skin", extras: { join: "narrow", wave: true, float: true, stand: true }, anchor: "periwinkle", second: "ice", feature: "a body of charge; storm-born", features: { ...EYES, ...sw("physiology.charged-body") }, finish: { "appearance.sheen": "glossy", "growth.branch-angle": "close", "growth.region-taper": "strong", "appearance.emission-brightness": "bright" }, glyphTop: ["..#..", ".#.#."] },
};

// The three authored frames, as frames.py defines them (open traits, pools, fixed values).
// The Loika's fixed measures, taken from the accepted Pip (art/miniature-lives, rich-plain 300×310 and
// hibit-plain 280×300; catalogue 9): a body 0.92 as tall as long and as round from the front; a head
// two thirds of the body, carried high and fused to it; eye rings 0.43 of the head's height, set wide
// and at the head's middle; a stub snout that is the whole lower face, cream like the belly; the belly
// field half the body's depth; legs a third of the body's height and a third as thick; feet a quarter
// of the body's length and a tenth of its height, rounded; a crest of three leaf sheets 0.6 of the head.
const S01_FIXED = {
  "growth.core-half-length": "medium", "growth.core-width-ratio": "wide", "growth.core-depth-ratio": "deep",
  "growth.head-length-ratio": "large", "growth.head-width-ratio": "high", "growth.head-depth-ratio": "high",
  "growth.head-lift-ratio": "high", "growth.muzzle-projection-ratio": "stub", "growth.muzzle-width-ratio": "full",
  "growth.exterior-eye-spacing-ratio": "wide", "growth.exterior-eye-height-ratio": "middle", "growth.crown-height-ratio": "high",
  "growth.support-drop-ratio": "short", "growth.support-radius-ratio": "stout", "growth.support-splay-ratio": "low",
  "growth.terminal-length-ratio": "narrow", "growth.terminal-depth-ratio": "small", "growth.belly-field-extent": "high",
  "anatomy.contact-terminal-form": "rounded", "anatomy.region-longitudinal-form": "ovoid", "anatomy.region-cross-exponent": "round",
  "appearance.marking-layout": "patches", "appearance.marking-extent": "high", "appearance.marking-scale": "high",
  "appearance.marking-contrast": "high", "cognition.exploration-tendency": "seeking", "cognition.arousal-threshold": "low",
};
const S02_FIXED = {
  "growth.core-half-length": "large", "growth.head-length-ratio": "small", "growth.head-width-ratio": "low",
  "growth.head-depth-ratio": "low", "growth.head-lift-ratio": "low", "growth.exterior-eye-size-ratio": "large",
  "growth.exterior-eye-spacing-ratio": "wide", "movement.membrane-stroke": "low", "movement.membrane-coordination": "high",
  "energy.actuator-capacity": "low", "energy.reserve-capacity": "high", "energy.action-efficiency": "low",
};
const S03_FIXED = {
  "growth.core-half-length": "small", "growth.head-length-ratio": "medium", "growth.head-width-ratio": "high",
  "growth.head-depth-ratio": "high", "growth.head-lift-ratio": "low", "growth.join-throat-ratio": "broad",
  "growth.support-splay-ratio": "high", "anatomy.region-cross-exponent": "round", "anatomy.region-longitudinal-form": "tapered",
};

const row = (code, clan, size, tier, kind, moves, habitat, gate, diet, ability, character) => ({ id: code, name: SPECIES_NAMES[code] ?? code, plural: SPECIES_NAMES[code] ?? code, order: Number(code.slice(1)), clan, size, tier, seed: 1, taxonomy: { code, resembles: kind, moves, habitat, gate, diet, ability, character } });

export const SPECIES = [
  { ...row("S01", "C01", "medium", "starter", "a round frog-hare, Pip (frame hopper)", "hops", "meadow, pond edge", null, "fruit", "calms wary creatures", "gentle and curious, a little shy"),
    summary: "The starter: Pip as in the approved art. Exactly the five open traits of the Pip proof.",
    fixed: S01_FIXED, typical: { "growth.exterior-eye-size-ratio": "huge" }, openSwitches: ["appearance.marking-switch", "anatomy.crown-presence"],
    open: [
      { chapter: "coat", id: "markings", name: "Markings", loci: ["appearance.marking-switch"], looks: ["plain", "pale patches"] },
      { chapter: "face", id: "crown", name: "Crown", loci: ["anatomy.crown-presence"], looks: ["bare head", "leaf crest"] },
      { chapter: "face", id: "eye-rings", name: "Eye rings", loci: ["growth.exterior-eye-size-ratio"], looks: ["thin rings", "between", "wide pale rings"], pool: { "growth.exterior-eye-size-ratio": ["large", "huge"] } },
      { chapter: "movement", id: "drive", name: "Drive", loci: ["movement.cycle-rate"], looks: ["steady", "between", "bursts"] },
      { chapter: "stamina", id: "efficiency", name: "Efficiency", loci: ["energy.action-efficiency"], looks: ["thrifty", "between", "ordinary"] },
    ],
    sealed: {}, glyph: ["#.#.#", ".###.", "#####", "#####", "#.#.#"],
    pending: [{ trait: "orange eyes", why: "eye rim and pupil are fixed inks" }] },
  { ...row("S02", "C02", "large", "early", "a puffball under a cap (frame puffcap)", "waddles", "wood, meadow, pond", "Character sealed (a crystal)", "fruit", "sniffs out buried pods; sheds after a full meal", "a sleepy glutton nothing startles"),
    summary: "A radial, capped plan: a round furred body, a face, a cap on top, no legs. It waddles.",
    fixed: S02_FIXED, openSwitches: ["appearance.marking-switch"],
    open: [
      { trait: "colour", pool: { "appearance.body-palette": ["coral", "raspberry", "marigold", "plum"] }, looks: ["coral", "raspberry", "marigold", "plum", "two side by side"] },
      { trait: "markings", name: "Spots", looks: ["bare", "bands", "spots", "bands and spots"] },
      { trait: "fluff" }, { trait: "roundness" }, { trait: "body" },
      { chapter: "shape", id: "cap-size", name: "Cap size", loci: ["growth.wing-span-ratio", "growth.wing-chord-ratio"], looks: ["small cap", "between", "wide cap"] },
      { trait: "cap-colour" }, { trait: "cap-spots" },
      { trait: "pace" }, { trait: "turning" },
      { chapter: "movement", id: "waddle", name: "Waddle", loci: ["movement.axial-amplitude", "movement.axial-phase"], looks: ["slight sway", "between", "big waddle"] },
      { trait: "curiosity" }, { trait: "nerve" },
    ],
    sealed: { character: "a vybronic crystal, dug up where an Untuva partner sniffs out a buried pod" }, glyph: [".###.", "#####", "#####", ".#.#.", ".###."], pod: { second: "marigold" } },
  { ...row("S03", "C03", "small", "mid", "a lizard with a lantern tail (frame glowtail)", "scurries, digs", "wood, rock field", "opens narrow holes and Night", "dew", "digs narrow burrows; lights fog and Night", "a brave little torchbearer"),
    summary: "A tailed, scaled burrower: a low two-part body, four short legs, a crest, a long tail that carries the glow.",
    fixed: S03_FIXED, openSwitches: ["appearance.marking-switch"],
    open: [
      { trait: "colour", pool: { "appearance.body-palette": ["lagoon", "jade", "marigold", "periwinkle"] }, looks: ["lagoon", "jade", "marigold", "periwinkle", "two side by side"] },
      { trait: "second-colour", name: "Leg colour", pool: { "appearance.underside-palette": ["milk-mint", "cream", "ice", "slate"] }, looks: ["milk-mint", "cream", "ice", "slate", "two side by side"] },
      { trait: "markings", looks: ["plain", "stripes", "spots", "stripes and spots"] }, { trait: "scales" },
      { chapter: "face", id: "crest", name: "Crest", loci: ["growth.crown-height-ratio"], looks: ["low crest", "between", "tall crest"] },
      { trait: "eyes" }, { trait: "snout" }, { trait: "build" }, { trait: "hind-body" }, { trait: "back-line" },
      { chapter: "legs-tail", id: "legs", name: "Legs", loci: ["growth.support-drop-ratio", "growth.support-radius-ratio"], looks: ["short, fine", "between", "long, stout"] },
      { trait: "feet", name: "Claws", shapeable: false, override: "breeding only: the claws are how a Tuikis digs, a field ability, so they change like a doing" },
      { trait: "tail" }, { trait: "tail-curl" }, { trait: "pace" }, { trait: "stride" },
      { chapter: "movement", id: "weave", name: "Weave", loci: ["movement.axial-amplitude", "movement.axial-phase"], looks: ["straight scurry", "between", "weaving glide"] },
      { trait: "turning" }, { trait: "strength" }, { trait: "reserve" }, { trait: "thrift" }, { trait: "curiosity" }, { trait: "nerve" },
      { trait: "glow", shapeable: false }, { trait: "glow-length", shapeable: false },
    ],
    sealed: {}, glyph: ["..#..", ".###.", "..#..", "..#..", "#####"], pod: { second: "marigold" } },
  { ...row("S04", "C04", "medium", "starter", "a cat", "prowls, pounces", "wood, meadow", null, "fruit", "creeps up without startling anything", "aloof at first, then devoted"), sealed: {}, alwaysOpen: ["ears", "tail"] },
  { ...row("S05", "C05", "medium", "early", "a fox", "trots", "meadow, wood edge", null, "fruit, seeds", "senses warm stones (Energy)", "quick and clever"), sealed: {}, alwaysOpen: ["fur-reach", "snout"] },
  { ...row("S06", "C06", "medium", "early", "a raccoon", "ambles, climbs", "pond edge, wood", null, "fruit, washed first", "lifts slabs to find what is under them", "nosy, a cheerful mischief-maker"), sealed: {}, alwaysOpen: ["mask", "rings"] },
  { ...row("S07", "C07", "large", "mid", "a badger or small bear", "lumbers, digs", "rock field, cave", "Deep ground", "fruit, roots", "digs through to Deep ground", "slow, stubborn, protective"), sealed: {}, alwaysOpen: ["feet", "mask"] },
  { ...row("S08", "C08", "large", "mid", "a goat or deer", "bounds, climbs", "rock field, meadow", null, "leaves, fruit", "climbs cliff steps that block other partners", "sure-footed and proud"), sealed: {}, alwaysOpen: ["horns", "legs"] },
  { ...row("S09", "C09", "large", "late", "a big bird", "strides, soars", "meadow, rock field", "Weather expeditions", "fruit, seeds", "scouts from above: reveals the cells around", "watchful, lordly"), sealed: { movement: "a tide pearl" }, alwaysOpen: ["flaps", "beak", "feathers", "feather-crest"] },
  { ...row("S10", "C10", "medium", "mid", "an otter", "swims, slides", "pond, fast water", "opens fast water", "fruit", "swims fast water", "playful, never still"), sealed: {}, alwaysOpen: ["tail", "build"] },
  { ...row("S11", "C11", "large", "late", "a turtle", "plods, swims slowly", "pond edge", "beyond fast water", "moss, fruit", "carries one more pod", "an old soul, patient"), sealed: { stamina: "a storm-glass shard" }, alwaysOpen: ["shell", "shell-plates", "scales"] },
  { ...row("S12", "C12", "small", "early", "a moth or butterfly", "flutters", "meadow", null, "dew", "finds dew (Essence)", "flighty and bright"), sealed: {}, alwaysOpen: ["flap-markings", "translucency", "flaps"] },
  { ...row("S13", "C13", "small", "mid", "a beetle", "crawls", "rock field, cave", null, "moss", "burrows under stones for buried finds", "a sturdy little tank"), sealed: {}, alwaysOpen: ["wing-cases", "antennae"] },
  { ...row("S14", "C14", "small", "early", "a slug", "slides", "pond edge, wood; out in fog banks", null, "moss", "leaves a sheen trail back to the start", "unhurried and sweet"), sealed: {}, alwaysOpen: ["skirt", "sheen"] },
  { ...row("S15", "C15", "medium", "late", "a walking plant", "walks on its roots", "wood", "sealed chapter", "light and dew", "roots for a turn; a bush grows where it stood", "patient, faintly wise"), sealed: { stamina: "a storm-glass shard" }, alwaysOpen: ["leaves", "light-feeding", "rays"] },
  { ...row("S16", "C16", "medium", "late", "a wisp of lightning (spectral, energy)", "floats, ripples", "meadow, rock field, only in a storm", "Charge sealed (storm-glass shard)", "Energy from struck stones", "draws a stray strike to itself", "wild and electric, rarely still"), sealed: { charge: "a storm-glass shard" }, alwaysOpen: ["charge", "phase", "pull", "glow"] },
];

// Generated species open Glow only where the plan draws an emission (a bulb or a charged body);
// elsewhere emission is a carried trunk locus the species fixes.
const GLOW_CLANS = new Set(["C03", "C16"]);

export function specOf(species) {
  const clan = CLANS[species.clan];
  const member = SPECIES.filter((s) => s.clan === species.clan).indexOf(species) + 1;
  // Proportions by kind (proportions.mjs): locked where the trait is closed, the type specimen's
  // typical copies where it is open; the clan finish sits under them, an authored species list above.
  const proportions = proportionPairs(species.id);
  return {
    ...species,
    plan: { key: clan.plan, extras: clan.extras }, anchor: clan.anchor, second: clan.second, feature: clan.feature,
    features: { ...clan.features },
    fixed: { "growth.core-half-length": species.size, ...clan.finish, ...proportions, ...(species.fixed ?? {}) }, finish: clan.finish,
    typical: { ...proportions, ...(species.typical ?? {}) },
    neverOpen: GLOW_CLANS.has(species.clan) ? [] : ["glow", "glow-length"],
    taxonomy: { ...species.taxonomy, resembles: clan.resembles, clanName: CLAN_NAMES[species.clan] ?? null, clanNumber: clan.number, member, speciesNumber: clan.number * 32 + member, size: species.size },
    glyph: species.glyph ?? [...clan.glyphTop, ...glyphRows(`${species.clan}:${species.id}`)],
  };
}
function glyphRows(seed) {
  let a = 0;
  for (const ch of seed) a = (Math.imul(a ^ ch.charCodeAt(0), 0x01000193) + 7) >>> 0;
  const rows = [];
  for (let i = 0; i < 3; i++) {
    const half = [0, 1, 2].map(() => { a = (Math.imul(a, 1664525) + 1013904223) >>> 0; return a >>> 31 ? "#" : "."; });
    if (half.join("") === "...") half[2] = "#";
    rows.push([...half, half[1], half[0]].join(""));
  }
  return rows;
}
