// Robustness test: N random genomes on the real catalogue (worked hopper frame,
// 57 heritable parts), rendered at 300/200/120 px under each distortion, plus
// the Caddy print case and the limit sweeps. Writes tests/results.md and
// tests/results.json and prints the tables.
//
//   node tests/run.mjs [--n 100] [--sweep-n 40] [--workers 4] [--quick]
import { Worker, isMainThread, parentPort, workerData } from "node:worker_threads";
import { writeFileSync } from "node:fs";
import { availableParallelism } from "node:os";

if (!isMainThread) {
  const { runScreen, runPrint, SCREEN, STRESS } = await import("./cases.mjs");
  parentPort.on("message", (t) => {
    if (t === null) return process.exit(0);
    let res;
    if (t.kind === "screen") {
      const all = [...SCREEN, ...STRESS];
      const conds = t.conds ? all.filter((c) => t.conds.includes(c.id)) : SCREEN;
      res = runScreen(t.i, t.D, t.seed, conds);
    } else res = { print: runPrint(t.i, t) };
    parentPort.postMessage({ t, res });
  });
  parentPort.postMessage(null);
} else {
  const arg = (k, d) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? Number(process.argv[i + 1]) : d; };
  const quick = process.argv.includes("--quick");
  const N = arg("n", quick ? 8 : 100), NS = arg("sweep-n", quick ? 6 : 40);
  const workers = arg("workers", Math.max(1, Math.min(8, availableParallelism())));
  const { SCREEN, STRESS } = await import("./cases.mjs");
  const tasks = [];
  for (const D of [300, 200, 120]) for (let i = 0; i < N; i++) tasks.push({ kind: "screen", group: "screen", i, D, seed: 1 });
  for (const mm of [20, 30]) for (let i = 0; i < N; i++) tasks.push({ kind: "print", group: "print", i, mm, dpi: 203, pxPerMm: 9, seed: 2 });
  for (const D of [100, 90, 80, 70, 60]) for (let i = 0; i < NS; i++) tasks.push({ kind: "screen", group: "sweepD", i, D, seed: 3, conds: ["clean", "all"] });
  for (const mm of [10, 12, 14, 16, 18, 20]) for (const pxPerMm of [9, 6]) for (let i = 0; i < NS; i++) tasks.push({ kind: "print", group: "sweepMM", i, mm, dpi: 203, pxPerMm, seed: 4 });
  for (let i = 0; i < NS; i++) tasks.push({ kind: "screen", group: "stress", i, D: 200, seed: 6, conds: STRESS.map((c) => c.id) });
  for (const dpi of [100, 125, 150, 300]) for (let i = 0; i < NS; i++) tasks.push({ kind: "print", group: "sweepDPI", i, mm: 20, dpi, pxPerMm: 9, seed: 5 });

  const results = [];
  const t0 = Date.now();
  let next = 0, done = 0;
  await new Promise((resolve) => {
    let alive = workers;
    for (let w = 0; w < workers; w++) {
      const wk = new Worker(new URL(import.meta.url));
      const feed = () => wk.postMessage(next < tasks.length ? tasks[next++] : null);
      wk.on("message", (m) => {
        if (m) {
          results.push(m);
          if (++done % 50 === 0) process.stderr.write(`  ${done}/${tasks.length} (${((Date.now() - t0) / 1000).toFixed(0)} s)\n`);
        }
        feed();
      });
      wk.on("exit", () => { if (--alive === 0) resolve(); });
    }
  });

  const pct = (a) => (a.n ? `${((100 * a.ok) / a.n).toFixed(a.ok === a.n || a.ok === 0 ? 0 : 1)}%` : "–");
  const cell = () => ({ n: 0, ok: 0, fa: 0, errors: {}, ms: 0 });
  const add = (c, r) => {
    c.n++; c.ok += r.ok ? 1 : 0; c.fa += r.falseAccept ? 1 : 0; c.ms += r.ms;
    if (!r.ok) { const e = (r.error || "?").replace(/\d+/g, "#"); c.errors[e] = (c.errors[e] || 0) + 1; }
  };
  const table = {};
  const get = (key) => (table[key] ??= cell());
  for (const { t, res } of results) {
    if (t.kind === "screen") for (const [cid, r] of Object.entries(res)) add(get(`${t.group}|${cid}|${t.D}`), r);
    else add(get(`${t.group}|${t.mm}|${t.dpi}|${t.pxPerMm}`), res.print);
  }
  const fa = Object.values(table).reduce((s, c) => s + c.fa, 0);
  const total = Object.values(table).reduce((s, c) => s + c.n, 0);
  const topErr = (c) => Object.entries(c.errors).sort((a, b) => b[1] - a[1]).slice(0, 2).map(([e, k]) => `${e} (${k})`).join("; ");

  const md = [];
  md.push(`Generated by \`node tests/run.mjs --n ${N} --sweep-n ${NS}\` (${new Date().toISOString().slice(0, 10)}). ${total} decodes, ${fa} false accepts (check passed on a wrong genome).`, "");
  md.push(`### Screen ring, ${N} random genomes per cell`, "");
  md.push("| Condition | 300 px | 200 px | 120 px |", "| --- | --- | --- | --- |");
  for (const c of SCREEN) md.push(`| ${c.label} | ${[300, 200, 120].map((D) => pct(get(`screen|${c.id}|${D}`))).join(" | ")} |`);
  const ms = [300, 200, 120].map((D) => { const cs = SCREEN.map((c) => get(`screen|${c.id}|${D}`)); return (cs.reduce((s, c) => s + c.ms, 0) / cs.reduce((s, c) => s + c.n, 0)).toFixed(0); });
  md.push("", `Mean decode time in Node: ${ms.join(" / ")} ms at 300 / 200 / 120 px.`, "");
  md.push(`### Caddy print, monochrome at 203 dpi, photographed at 9 px/mm (${N} genomes)`, "");
  md.push("| Print | Dots across | Success | Main failure |", "| --- | --- | --- | --- |");
  for (const mm of [20, 30]) { const c = get(`print|${mm}|203|9`); md.push(`| ${mm} mm | ${((mm / 25.4) * 203).toFixed(0)} | ${pct(c)} | ${topErr(c) || "–"} |`); }
  md.push("", `### Limits (${NS} genomes per cell)`, "");
  md.push("| Screen diameter | Clean | All distortions |", "| --- | --- | --- |");
  for (const D of [120, 100, 90, 80, 70, 60]) {
    const a = D === 120 ? get(`screen|clean|120`) : get(`sweepD|clean|${D}`), b = D === 120 ? get(`screen|all|120`) : get(`sweepD|all|${D}`);
    md.push(`| ${D} px | ${pct(a)} | ${pct(b)} |`);
  }
  md.push("", "| Print at 203 dpi | Dots across | Photo 9 px/mm | Photo 6 px/mm | Main failure |", "| --- | --- | --- | --- | --- |");
  for (const mm of [10, 12, 14, 16, 18, 20]) {
    const a = get(`sweepMM|${mm}|203|9`), b = get(`sweepMM|${mm}|203|6`);
    md.push(`| ${mm} mm | ${((mm / 25.4) * 203).toFixed(0)} | ${pct(a)} | ${pct(b)} | ${topErr(a) || topErr(b) || "–"} |`);
  }
  md.push("", "| 20 mm print at | Dots across | Photo 9 px/mm | Main failure |", "| --- | --- | --- | --- |");
  for (const dpi of [100, 125, 150, 203, 300]) {
    const c = dpi === 203 ? get(`print|20|203|9`) : get(`sweepDPI|20|${dpi}|9`);
    md.push(`| ${dpi} dpi | ${((20 / 25.4) * dpi).toFixed(0)} | ${pct(c)} | ${topErr(c) || "–"} |`);
  }
  md.push("", "| Beyond the targets, at 200 px | Success | Main failure |", "| --- | --- | --- |");
  for (const c of STRESS) { const x = get(`stress|${c.id}|200`); md.push(`| ${c.label} | ${pct(x)} | ${topErr(x) || "–"} |`); }
  md.push("", "Failure modes per cell (screen):", "");
  for (const c of SCREEN) for (const D of [300, 200, 120]) { const e = topErr(get(`screen|${c.id}|${D}`)); if (e) md.push(`- ${c.label}, ${D} px: ${e}`); }
  for (const D of [100, 90, 80, 70, 60]) for (const id of ["clean", "all"]) { const e = topErr(get(`sweepD|${id}|${D}`)); if (e) md.push(`- ${id}, ${D} px: ${e}`); }
  const text = md.join("\n") + "\n";
  writeFileSync(new URL("./results.md", import.meta.url), text);
  writeFileSync(new URL("./results.json", import.meta.url), JSON.stringify({ N, NS, table }, null, 1));
  console.log(text);
  console.error(`done in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
