// Snapshots the real species frames (design/proposals/species-frames/*.json,
// on the pinned 114-pair catalogue) into src/frames-data.mjs, so the encoder,
// the decoder and the offline scan page carry the same registry.
//   node tools/extract-frames.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { CATALOGUE } from "../src/catalogue-data.mjs";

const byId = new Map(CATALOGUE.loci.map((l) => [l.id, l]));
const SPECIES = [["species-hopper.json", 11], ["species-puffcap.json", 12], ["species-glowtail.json", 13]];
const frames = SPECIES.map(([file, species]) => {
  const d = JSON.parse(readFileSync(new URL(`../../../design/proposals/species-frames/${file}`, import.meta.url), "utf8"));
  const loci = new Map(d.loci.map((l) => [l.id, l]));
  return {
    species, version: 1, id: d.species.id, name: d.species.name, glyph: d.glyph,
    chapters: d.chapters.map((ch) => ({
      name: ch.name, sealed: !!ch.sealed,
      loci: ch.traits.flatMap((t) => t.loci.map((id) => ({ id, trait: t.name, alleles: byId.get(id).alleles, pool: loci.get(id).alleles, copies: 2 }))),
    })),
    // locked loci: one value each (both copies equal), as catalogue allele indexes
    locked: d.loci.filter((l) => l.kind === "locked").map((l) => [l.id, Math.max(0, byId.get(l.id).alleles.indexOf(l.copies[0]))]),
  };
});
const text = "// Generated by tools/extract-frames.mjs from design/proposals/species-frames/*.json. Do not edit.\n" +
  `export const FRAME_DATA = ${JSON.stringify({ catalogue: { id: CATALOGUE.id, version: CATALOGUE.version, digest: CATALOGUE.digest }, frames })};\n`;
writeFileSync(new URL("../src/frames-data.mjs", import.meta.url), text);
console.log(frames.map((f) => `${f.name} ${f.chapters.reduce((s, c) => s + c.loci.length, 0)} open, ${f.locked.length} locked`).join("; "));
