// Snapshots the species frames into src/frames-data.mjs, so the encoder, the decoder and the offline
// scan page carry one registry, append-only:
//   - the current frames, from the workbench registry (prototypes/workbench/frames/*.json,
//     mb-species-frame/2 on catalogue mb-genome-framework@9): species number = the species' order
//     (S01 = 1 … S16 = 16), frame version = the registry's frame version;
//   - the legacy frames already in the snapshot (species 11–13, version 1, on catalogue 6), kept as
//     they are so an old print decodes for as long as its frame is carried.
// A locus packs a copy as its index among the catalogue's alleles (ceil(log2 n) bits); a continuous
// locus also carries its alleles' values, so a blended copy (a number, the cross) is stamped as its
// bin, the nearest named allele.
//   node tools/extract-frames.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { CATALOGUE as WORKBENCH, LOCI } from "../../workbench/framework/catalogue.mjs";
import { FRAME_VERSION } from "../../workbench/framework/species.mjs";

const registryUrl = new URL("../../workbench/frames/", import.meta.url);
const index = JSON.parse(readFileSync(new URL("index.json", registryUrl), "utf8"));
let legacy = [];
try { legacy = (await import("../src/frames-data.mjs")).FRAME_DATA.frames.filter((f) => f.legacy); } catch { /* first run: nothing to carry */ }
const frames = index.species.map((s) => {
  const d = JSON.parse(readFileSync(new URL(s.file, registryUrl), "utf8"));
  const byId = new Map(d.loci.map((l) => [l.id, l]));
  const locusOf = (id) => {
    const cat = LOCI.get(id), row = byId.get(id);
    const alleles = cat.alleles.map((a) => a.id);
    const numeric = cat.operator === "copy-mean" && cat.alleles.every((a) => typeof a.value === "number");
    return { id, trait: row.trait, alleles, ...(numeric ? { values: cat.alleles.map((a) => a.value) } : {}), pool: row.alleles, copies: 2 };
  };
  return {
    species: d.species.order, version: d.frameVersion ?? FRAME_VERSION, id: d.species.id, name: d.species.name, glyph: d.glyph,
    chapters: d.chapters.map((ch) => ({ name: ch.name, sealed: !!ch.sealed, loci: ch.traits.flatMap((t) => t.loci.map(locusOf)) })),
    // locked loci: one value each (both copies equal), as catalogue allele indexes; the border seed
    locked: d.loci.filter((l) => l.kind === "locked").map((l) => [l.id, Math.max(0, LOCI.get(l.id).alleles.findIndex((a) => a.id === l.copies[0]))]),
  };
});
const all = [...legacy, ...frames];
const dup = all.map((f) => `${f.species}.${f.version}`).filter((k, i, a) => a.indexOf(k) !== i);
if (dup.length) throw new Error(`frame keys collide: ${dup.join(", ")}`);
const text = "// Generated by tools/extract-frames.mjs from prototypes/workbench/frames/*.json (the legacy frames carried over). Do not edit.\n" +
  `export const FRAME_DATA = ${JSON.stringify({ catalogue: { id: WORKBENCH.id, version: WORKBENCH.version, schema: index.catalogue, frameVersion: FRAME_VERSION }, legacyCatalogue: { id: "genomic-compositional-source-experiment", version: 6, digest: "0cdfdf47dbef5b20f36fb0d5e86c324e6a5d074bfbb8422f802bfe7866254beb" }, frames: all })};\n`;
writeFileSync(new URL("../src/frames-data.mjs", import.meta.url), text);
console.log(all.map((f) => `${f.id} ${f.name} ${f.species}.${f.version}: ${f.chapters.reduce((s, c) => s + c.loci.length, 0)} open, ${f.locked.length} locked${f.legacy ? " (legacy)" : ""}`).join("\n"));
