// Snapshots the species frames into src/frames-data.mjs, so the encoder, the decoder and the offline
// scan page carry one registry, append-only:
//   - the current frames, from the workbench registry (prototypes/workbench/frames/*.json,
//     mb-species-frame/2 on catalogue mb-genome-framework@9): species number = the species' order
//     (S01 = 1 … S16 = 16), frame version = the registry's frame version;
//   - every frame already in the snapshot that the registry no longer builds at that version (the
//     legacy frames, species 11–13, version 1, on catalogue 6; the sixteen at frame version 2), kept
//     as they are so an old print decodes for as long as its frame is carried. A frame already in
//     the snapshot is never rewritten: if the registry builds the same species and version with
//     different content, this stops (a changed frame is a new frame version).
// A locus packs a copy as its index among the catalogue's alleles (ceil(log2 n) bits); a continuous
// locus also carries its alleles' values, so a blended copy (a number, the cross) is stamped as its
// bin, the nearest named allele.
//   node tools/extract-frames.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { CATALOGUE as WORKBENCH, LOCI } from "../../workbench/framework/catalogue.mjs";
import { FRAME_VERSION } from "../../workbench/framework/species.mjs";

const registryUrl = new URL("../../workbench/frames/", import.meta.url);
const index = JSON.parse(readFileSync(new URL("index.json", registryUrl), "utf8"));
let carried = [];
const snapshot = new URL("../src/frames-data.mjs", import.meta.url);
if (existsSync(snapshot)) carried = (await import(snapshot.href)).FRAME_DATA.frames; // any error here (a truncated snapshot) stops the tool: never rewrite from a partial read
// else first run: nothing to carry
const frames = index.species.map((s) => {
  const d = JSON.parse(readFileSync(new URL(s.file, registryUrl), "utf8"));
  const byId = new Map(d.loci.map((l) => [l.id, l]));
  const locusOf = (id) => {
    const cat = LOCI.get(id), row = byId.get(id);
    const alleles = cat.alleles.map((a) => a.id);
    const numeric = cat.operator === "copy-mean" && cat.alleles.every((a) => typeof a.value === "number");
    return { id, trait: row.trait, alleles, ...(numeric ? { values: cat.alleles.map((a) => a.value) } : {}), pool: row.alleles, copies: 2 };
  };
  return {
    species: d.species.order, version: d.frameVersion ?? FRAME_VERSION, id: d.species.id, name: d.species.name, glyph: d.glyph,
    chapters: d.chapters.map((ch) => ({ name: ch.name, sealed: !!ch.sealed, loci: ch.traits.flatMap((t) => t.loci.map(locusOf)) })),
    // locked loci: one value each (both copies equal), as catalogue allele indexes; the border seed
    locked: d.loci.filter((l) => l.kind === "locked").map((l) => [l.id, Math.max(0, LOCI.get(l.id).alleles.findIndex((a) => a.id === l.copies[0]))]),
  };
});
const keyOf = (f) => `${f.species}.${f.version}`;
const same = new Map(carried.map((f) => [keyOf(f), f]));
for (const f of frames) {
  const old = same.get(keyOf(f));
  if (old && JSON.stringify(old) !== JSON.stringify(f)) throw new Error(`frame ${keyOf(f)} (${f.id}) is already in the registry with different content: the registry is append-only, bump the frame version`);
}
const fresh = new Set(frames.map(keyOf));
const all = [...carried.filter((f) => !fresh.has(keyOf(f))), ...frames];
const dup = all.map((f) => `${f.species}.${f.version}`).filter((k, i, a) => a.indexOf(k) !== i);
if (dup.length) throw new Error(`frame keys collide: ${dup.join(", ")}`);
const outKeys = new Set(all.map(keyOf));
const lost = carried.map(keyOf).filter((k) => !outKeys.has(k));
if (lost.length) throw new Error(`the snapshot would lose frames: ${lost.join(", ")}`);
const text = "// Generated by tools/extract-frames.mjs from prototypes/workbench/frames/*.json (the legacy frames carried over). Do not edit. Append-only: older frames are carried beside the current ones.\n" +
  `export const FRAME_DATA = ${JSON.stringify({ catalogue: { id: WORKBENCH.id, version: WORKBENCH.version, schema: index.catalogue, frameVersion: FRAME_VERSION }, legacyCatalogue: { id: "genomic-compositional-source-experiment", version: 6, digest: "0cdfdf47dbef5b20f36fb0d5e86c324e6a5d074bfbb8422f802bfe7866254beb" }, frames: all })};\n`;
writeFileSync(new URL("../src/frames-data.mjs", import.meta.url), text);
console.log(all.map((f) => `${f.id} ${f.name} ${f.species}.${f.version}: ${f.chapters.reduce((s, c) => s + c.loci.length, 0)} open, ${f.locked.length} locked${f.legacy ? " (legacy)" : ""}`).join("\n"));
