import { mkdir, writeFile } from 'node:fs/promises';
import { emptyEnvelope, applyCommand, creationRequest } from './domain.mjs';
import { sources } from './content.mjs';
import { initialController } from './controller.mjs';
import { mapView } from './view.mjs';
import { renderLab } from './render.mjs';
import { encodePng } from '../pixel/png.mjs';

const output = new URL('./artifacts/', import.meta.url);
await mkdir(output, { recursive: true });
let envelope = emptyEnvelope();
const states = [];
function capture(name, page, extra = {}) {
  states.push({ name, state: { ...initialController(envelope), page, ...extra } });
}
function command(value) { envelope = applyCommand(envelope, value).envelope; }

capture('01-lab', 'lab');
capture('02-receive', 'receive', { focus: 0 });
capture('02-pending-receipt', 'receive', { focus: 0, busy: true });
command({ type: 'receive' });
capture('02-received', 'received');
capture('03-question', 'study', { focus: 0, sampleId: sources.probe.id });
command({ type: 'start', sampleId: sources.probe.id, question: 'structure' });
capture('04-research', 'research');
command({ type: 'advance' });
capture('05-finding', 'finding');
capture('05-direction', 'direction', { focus: 0 });
command({ type: 'direction', direction: 'shape' });
capture('06-preview', 'create', { focus: 0 });
command({ type: 'intent', id: 'ARTIFACT-001', request: creationRequest(envelope) });
capture('06-checking', 'checking');
command({ type: 'resolve', id: 'ARTIFACT-001' });
capture('07-ready', 'ready');
capture('07-meet', 'meet');
capture('07-collection', 'collection');
capture('08-inspect', 'inspect', { focus: 0 });
capture('08-identity', 'detail', { detail: 'identity' });
capture('portrait-pending', 'meet', { portraitMissing: true });
capture('not-saved', 'error', { error: 'NOT SAVED - STORAGE ABORTED' });

envelope = emptyEnvelope();
command({ type: 'console' });
capture('03-question-variation', 'study', { focus: 1, sampleId: sources.console.id });
command({ type: 'start', sampleId: sources.console.id, question: 'variation' });
command({ type: 'advance' });
capture('05-finding-variation', 'finding');
capture('05-direction-variation', 'direction', { focus: 0 });
capture('05-clues-variation', 'detail', { detail: 'evidence' });

for (const { name, state } of states) {
  for (const profile of ['color', 'mono']) {
    const frame = renderLab(mapView(state), profile);
    for (const scale of [1, 3]) {
      await writeFile(new URL(`${name}-${profile}-${scale}x.png`, output), encodePng(frame, scale));
    }
  }
}
await writeFile(new URL('README.md', output), `# Founder loop fixture keyframes

Provisional authored content and pixel art. These images are generated by the same view mapper and renderer as the interactive host, from scripted saved fixture states; they are not browser interaction evidence or hardware screenshots.

The numbered files cover the eight UX steps, including deliberate Ready/Open/Meet. Extra files show pending receipt, unresolved operation, missing portrait and storage failure. Both color and monochrome have native 320 × 240 and nearest-neighbor 3× exports.

This illustrative field source is simulated, supplies zero resource entries, and consumes one fixture sample only. The saved authored outcome is Cc/Rr/Pp with crown and eye rings expressed and pale markings carried but unexpressed. Research focus does not alter genes. All individuals are explicitly parentless lab-created fixtures, separate from the breeding prototype collection.

Regenerate with node prototype/lab/export.mjs. Review limitations and interactive controls in ../README.md.
`);
console.log(`Exported ${states.length * 4} PNGs to ${output.pathname}`);
